[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/yahoo/*"
  to = "https://query1.finance.yahoo.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
